# email:
#   from: someuser@gmx.com
#   to:
#     - someuser@gmx.com
#   smtp_host: smtp.gmx.com
#   smtp_port: 25
#   smtp_username: someuser@gmx
#   smtp_password: XXXXXXX
#   template: html
tasks:
  # downloading task
  download-rss:
    # RSS where everything is downloaded from:
    rss: CONFIG_RSS_FEED
    # fetch all the feed series
    all_series: yes
    # use transmission to download the torrents
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      path: /home/osmc/Downloads
    # Remove completed downloads from Transmission
    clean_transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      finished_for: 1 hours
  # sorting task
  sort-files:
    find:
      # directory with the files to be sorted
      path: /home/osmc/Downloads/
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    disable:
      - seen
      - retry_failed
    # this is needed for the episode names
    thetvdb_lookup: yes
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    # TVDB doesn't recognise "Adventure Time with Finn and Jake" so you must add such exceptions here manually
    series:
      - Adventure Time
    move:
      # this is where the series will be put.
      to: /home/osmc/TV Shows/{{ tvdb_series_name }}/Season {{ tvdb_season|pad(2) }}
      # Set the filename E.g: "Series Name - S01E02 - Episode Name.mkv"
      filename: "{{ tvdb_series_name }} - {{ series_id|default('XX') }} {% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name }}{% endif %}{{ location|pathext }}"
    # Download subtitles of the Series in your chosen language:
    exec: /usr/local/bin/subliminal download -l "SUBTITLES_LANGUAGE" -s "/home/osmc/TV Shows/{{ tvdb_series_name }} - {{ series_id|default('XX') }} {% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name }}{% endif %}{{ location|pathext }}