# email:
#   from: someuser@gmx.com
#   to:
#     - someuser@gmx.com
#   smtp_host: smtp.gmx.com
#   smtp_port: 25
#   smtp_username: someuser@gmx
#   smtp_password: XXXXXXX
#   template: html

templates:
  # This template is used to sort the problematic series
  # http://flexget.com/Cookbook/Series/Sort
  # You must use series groups, so that we can turn off filtering with the parse_only option in our sort feed.
  tv-series:
    series:
      myseriesgroup:
        - Grey's Anatomy:
            set:
              tvdb_id: 73762
        - Designated Survivor

tasks:
  # downloading task
  download-rss:
    # RSS where everything is downloaded from:
    rss: CONFIG_RSS_FEED
    # fetch all the feed series
    all_series: yes
    # use transmission to download the torrents
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      path: /home/osmc/Downloads
    # Remove completed downloads from Transmission
    clean_transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
      finished_for: 1 hours
  # sorting task
  sort-files:
    filesystem:
      # directory with the files to be sorted
      path: /home/osmc/Downloads/
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    disable:
      - seen
      - retry_failed
    # this is needed for the episode names
    thetvdb_lookup: yes
    template: tv-series
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    # NOTE: You must set the parse_only option for all of the series groups you have configured in your template.
    # This option prevents the series plugin from accepting or rejecting anything in this feed.
    series:
      settings:
        myseriesgroup:
          parse_only: yes
    # Ignore samples
    regexp:
      reject:
        - sample
    # With the require_field and accept_all plugins, we accept anything that the series plugin has successfully parsed.
    require_field: series_name
    move:
      # this is where the series will be put.
      to: /home/osmc/TV Shows/{{ tvdb_series_name }}
      # If you want to rename the filename to something like "Series Name - S01E02 - Episode Name.mkv" uncomment the line below and
      # swap the "exec" below as well. It is commented by default as the service providing the metadata cannot always match.
      #filename: "{{ tvdb_series_name }} - {{ series_id|default('XX') }} {% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name }}{% endif %}{{ location|pathext }}"
    # Download all missing subtitles for this TV Show in your chosen language (subliminal will ignore series with subtitles already):
    exec: /usr/local/bin/subliminal download -l "SUBTITLES_LANGUAGE" -s "/home/osmc/TV Shows/{{ tvdb_series_name }}/"
    # Use this line instead if you choose to rename files:
    #exec: /usr/local/bin/subliminal download -l "SUBTITLES_LANGUAGE" -s "/home/osmc/TV Shows/{{ tvdb_series_name }}/{{ tvdb_series_name }} - {{ series_id|default('XX') }} {% if tvdb_ep_name|default(False) %} - {{ tvdb_ep_name }}{% endif %}{{ location|pathext }}"

